timezone: Europe/London

markdown: kramdown

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap

collections:
  - gallery
  - link

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
