timezone: Europe/London

markdown: kramdown

tumblr:
  api:
    endpoint: //api.tumblr.com/v2/blog/simonmayes.co.uk
    key: IqVMfNlzbFWoqLH7ESLRcY0ZxocWIopDFdZQaBVd3sJ3MNdNIh
    
gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
