timezone: Europe/London

markdown: kramdown

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap

collections:
  - gallery
  - links

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

sass:
  sass_dir: css/_sass
  style: :compressed
