timezone: Europe/London

markdown: kramdown

gems:
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-coffeescript

collections:
  - links

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

sass:
  sass_dir: css/_sass
  style: :compressed


my_categories:
  - climbing
  - technology

name: Type II Fun
description: Type II Fun. The personal blog and website of Simon Mayes. Climber and Software Engineer.
keywords: simon mayes, climber, software engineer, msyea
