timezone: Europe/London

markdown: kramdown
url: https://type2fun.net

gems:
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-coffeescript
  - jekyll-paginate

collections:
  - links

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - bower.json
  - circle.yml

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

sass:
  sass_dir: css/_sass
  style: :compressed


my_categories:
  - climbing
  - technology

paginate: 1

name: Type II Fun
description: Type II Fun. The personal blog and website of Simon Mayes. Climber and Software Engineer.
keywords: simon mayes, climber, software engineer, msyea
