timezone: Europe/London

markdown: kramdown

collections:
  - links

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

sass:
  sass_dir: css/_sass
  style: :compressed


my_categories:
  - climbing
  - technology

name: Because it's there
description: Because it's there. The personal blog and website of Simon Mayes. Climber and Software Engineer.
keywords: simon mayes, climber, software engineer, msyea
